spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cosmetics?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: alsrb!0119
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  messages:
    basename: messages

  jpa:
    hibernate:
      ddl-auto: create
      #ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    #root: warn
    org.hibernate.SQL: debug